version: '2'

volumes:
    pgdata:
        driver: local

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    pgsql:
        image: postgres:latest
        expose:
            - 5432
        volumes:
            - pgdata:/var/lib/postgresql/data/

    selenium:
        image: selenium/standalone-firefox:2.53.1-beryllium
        expose:
            - 4444

    builtin:
        build: ./docker/builtin/
        expose:
            - 8000
        volumes_from:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
