version: '3'

volumes:
    pgdata:
        driver: local

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html:ro
        depends_on:
            - php

    pgsql:
        image: postgres:latest
        expose:
            - 5432
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_PASSWORD: Wibble123!

    selenium:
        image: selenium/standalone-firefox:2.53.1-beryllium
        expose:
            - 4444

    builtin:
        build: ./docker/builtin/
        expose:
            - 8000
        volumes:
            - .:/var/www/html
        depends_on:
            - pgsql

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
        depends_on:
            - pgsql
            - mailcatcher

    mailcatcher:
        image: rylwin/mailcatcher
        ports:
            - 1080:1080
        expose:
            - 1025
