version: '2'

volumes:
    pgdata:
        driver: local

services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    pgsql:
        image: postgres:latest
        expose:
            - 5432
        volumes:
            - pgdata:/var/lib/postgresql/data/

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
