# known to work with Ansible 2.2.1.0
---
- hosts: all

  vars:
    general_password: "Wibble123!"
    home: "/home/vagrant/"
    moodledata: "{{ home }}moodledata/"
    dot_bashrc: "{{ home }}.bashrc"
    dot_profile: "{{ home }}.profile"
    php_ini: "/etc/php/5.6/fpm/php.ini"
    moodle_dir: "/vagrant/moodle/"
    config_php: "{{ moodle_dir }}config.php"
    composer: "/usr/local/bin/composer"
    xvfb_display_id: ":99"

  pre_tasks:
    - name: Timestamp provision
      shell: date >> /etc/vagrant_provisioned_at
      args:
        executable: /bin/bash
      changed_when: False
      become: true

  tasks:
    - name: Add PHP 5.6 apt repository
      apt_repository:
        repo: 'ppa:ondrej/php'
      become: true

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
      become: true

    - name: Install apt packages
      apt: name={{ item }} state=present
      with_items:
        - git
        - htop
        - vim
        - postgresql
        - postgresql-server-dev-9.3
        - nginx
        - python-software-properties
        - python-psycopg2
        - php5.6-cli
        - php5.6-curl
        - php5.6-fpm
        - php5.6-gd
        - php5.6-intl
        - php5.6-mbstring
        - php5.6-pgsql
        - php5.6-soap
        - php5.6-xdebug
        - php5.6-xml
        - php5.6-xmlrpc
        - php5.6-zip
        - default-jre
        - firefox
        - xvfb
      become: true

    - name: Set PostgreSQL database password
      command: psql -U postgres -d postgres -c "alter user postgres with password '{{ general_password }}';"
      become: true
      become_user: postgres
      changed_when: False

    - name: Protect .pgpass
      file: path="{{ home }}.pgpass" mode=0600 state=file

    - name: Create moodle database
      postgresql_db:
        name: moodle
      become: true
      become_user: postgres

    - name: Create moodledata directories
      file:
        path: "{{ moodledata }}{{ item }}"
        state: directory
        owner: vagrant
        group: www-data
        mode: 0775
        recurse: yes
      with_items:
        - main
        - phpu
        - behat
      become: true

    - name: Enable colour prompt in bash
      replace: dest={{ dot_bashrc }} regexp="^\#force_color_prompt\=yes$" replace="force_color_prompt=yes"

    - name: Template nginx server block
      template:
        src: nginx-server-block
        dest: /etc/nginx/sites-available/default
        owner: bin
        group: root
        mode: 0644
      become: true

    - name: Enable Xdebug
      ini_file: dest={{ php_ini }}
                section=xdebug option={{ item.key }}
                value={{ item.value }}
                state=present
                backup=yes
      with_items:
        - { key: "xdebug.remote_enable", value: "on" }
        - { key: "xdebug.remote_connect_back", value: "on" }
        - { key: "xdebug.remote_autostart", value: "on" }
      become: true

    - name: Stat Moodle's config.php
      stat: path={{ config_php }}
      register: moodle_config

    - name: Template Moodle's config.php
      template:
        src: config.php
        dest: "{{ config_php }}"
        owner: vagrant
        group: www-data
        mode: 0644
      when: moodle_config.stat.exists == False

    - name: Install Moodle database
      command: "/usr/bin/php {{ moodle_dir }}admin/cli/install_database.php --adminpass={{ general_password }} --agree-license --fullname=Moodle --shortname=Moodle"
      when: moodle_config.stat.exists == False
      become: true
      become_user: www-data

    - name: Setup Moodle cron
      cron: user=vagrant name="Moodle" job="/usr/bin/php {{ moodle_dir }}admin/cli/cron.php > /tmp/cron-moodle.txt" minute="0,10,20,30,40,50" state=present

    - name: Stat Composer (perm)
      stat: path={{ composer }}
      register: composer_perm

    - name: Install Composer into /tmp/
      # https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md
      shell: |
        EXPECTED_SIGNATURE=$(wget -q -O - https://composer.github.io/installer.sig)
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")

        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
        then
            >&2 echo 'ERROR: Invalid installer signature'
            rm composer-setup.php
            exit 1
        fi

        php composer-setup.php --quiet
        RESULT=$?
        rm composer-setup.php
        exit $RESULT
      args:
        chdir: /tmp/
      when: composer_perm.stat.exists == False

    - name: Stat Composer (temp)
      stat: path=/tmp/composer.phar
      register: composer_temp

    - name: Move Composer (temp) to somewhere on path (perm)
      command: mv /tmp/composer.phar {{ composer }}
      become: true
      when: composer_temp.stat.exists

    - name: Make Composer (perm) executable
      file:
        path: "{{ composer }}"
        mode: 0775
      become: true

    - name: Stat Moodle's vendor/ directory
      stat: path="{{ moodle_dir }}vendor"
      register: moodle_vendor

    - name: Install Moodle's Composer packages
      command: composer install
      args:
        chdir: "{{ moodle_dir }}"
      when: moodle_vendor.stat.exists == False

    - name: Stat project's vendor/ directory
      stat: path=/vagrant/vendor
      register: project_vendor

    - name: Install project's Composer packages
      command: composer install
      args:
        chdir: /vagrant/
      when: project_vendor.stat.exists == False

    - name: Check whether AU locale is installed
      shell: locale -a | grep -P "^en_AU$"
      register: au_locale_installed
      failed_when: False
      changed_when: False

    - name: Install AU locale (required for the PHPUnit test suite)
      command: "locale-gen {{ item }}"
      with_items:
        - en_AU
        - en_AU.UTF-8
      become: true
      when: au_locale_installed.stdout != "en_AU"

    - name: Stat an arbitrary phpunit.xml file
      stat: path="{{ moodle_dir }}admin/tool/behat/phpunit.xml"
      register: behat_phpunit

    - name: Build 'component configs'
      command: php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
      args:
        chdir: "{{ moodle_dir }}"
      when: behat_phpunit.stat.exists == False

    - name: Initialize Moodle test environments
      command: "php admin/tool/{{ item }}/cli/init.php"
      with_items:
        - phpunit
        - behat
      args:
        chdir: "{{ moodle_dir }}"
      when: moodle_config.stat.exists == False

    - name: Stat squizlabs
      stat: path="{{ home }}.config/composer/vendor/squizlabs"
      register: squizlabs

    - name: Install PHP Code Sniffer
      command: composer global require "squizlabs/php_codesniffer=*"
      when: squizlabs.stat.exists == False

    - name: Add global Composer bin directory to path
      lineinfile: dest={{ dot_profile }} line="PATH=\"$HOME/.config/composer/vendor/bin:$PATH\""

    - name: Add display id for Xvfb (for Behat)
      lineinfile: dest={{ dot_profile }} line="export DISPLAY={{ xvfb_display_id }}"

    - name: Check whether Xvfb is running
      shell: ps -elf | grep Xvfb | grep -v grep | grep -o Xvfb
      register: xvfb_running
      failed_when: False
      changed_when: False

    - name: Run Xvfb
      shell: "Xvfb {{ xvfb_display_id }} -ac >/dev/null 2>&1 &"
      when: xvfb_running.stdout != "Xvfb"

    - name: Clone Moodle local/codechecker repo
      git: repo=https://github.com/moodlehq/moodle-local_codechecker dest="{{ home }}.codechecker" version=v2.5.4 update=no

    - name: Turn on Moodle debugging and turn off JavaScript caching
      command: psql -U postgres -d moodle -a -f config.sql
      become: true
      become_user: postgres

    - name: Purge Moodle caches
      command: php admin/cli/purge_caches.php
      args:
        chdir: "{{ moodle_dir }}"

    - name: Restart services
      service: name={{ item }} state=restarted
      with_items:
        - postgresql
        - nginx
        - php5.6-fpm
      become: true
